version: "4.28"
services:
  chat-api:
    build:
      context: ./chat-api
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    volumes:
      - ./chat-api/src:/app/chat-api/src
  chat-gateway:
    build:
      context: ./chat-gateway
      dockerfile: Dockerfile.prod
    ports:
      - "3013:3013"
    environment:
      - PORT=3013
      - NODE_ENV=production
    volumes:
      - ./chat-gateway/src:/app/chat-gateway/src
  mongo:
    build:
      context: ./mongodb_rs
      args:
        MONGO_VERSION: 4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: chat-api
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - "27017:27017"
